[package]
name = "image2"
version = "1.0.0-beta.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["image", "image-processing"]
repository = "https://github.com/zshipko/image2-rs"
documentation = "https://docs.rs/image2"
description = "A simple image processing library"
readme = "README.md"
edition = "2018"


[dependencies]
half = "1"
thiserror = "1"
euclid = "0.22"
cpp = {version = "0.5", optional = true}
rayon = {version = "1", optional = true}
serde = {version = "1", optional = true, features = ["derive"]}
halide-runtime = {version = "0.5", optional = true}
bevy = {version = "0.2", default-features=false, optional = true, features=[
    "bevy_audio",
    "bevy_gilrs",
    "bevy_gltf",
    "bevy_wgpu",
    "bevy_winit",
    "render",
    "dynamic_plugins",
    "mp3",
    "x11",
]}
bevy_asset = {version = "0.2", optional = true}
bevy_render = {version = "0.2", optional = true}
bevy_math = {version = "0.2", optional = true}
anyhow = {version = "1", optional = true}

[build-dependencies]
cpp_build = {version = "0.5", optional = true}

[dev-dependencies]
smol = "1"

[features]
default = ["oiio", "parallel"]
ui = ["bevy", "bevy_asset", "bevy_render", "bevy_math", "anyhow"]
oiio = ["cpp", "cpp_build"]
parallel = ["rayon"]
halide = ["halide-runtime"]
docs-rs = []

[package.metadata.docs.rs]
features = ["docs-rs", "oiio", "parallel", "halide"]

[[example]]
name = "display"
required-features = ["ui"]
